ALLOWED_ORIGIN=http://localhost:4200
DISABLE_EMAIL=true
EXPORT_ROOT_DIR=/epic-export
TEMPLATES_ROOT_DIR=/epic-templates
CLIENT_LOGS_DIR=/epic-client-logs
DATABASE_NAME=epiclocaldb
ATTACHMENT_MAX_ALLOWED_FILE_SIZE_BYTES=16106127360
THREADS_FOR_INDEXING=20
SYNCHRONOUS_CLASSES_FOR_INDEXING=2
PERFORM_INDEXING=TRUE
