ALLOWED_ORIGIN={{ORIGIN_URL}}
DISABLE_EMAIL={{DISABLE_EMAIL}}
EXPORT_ROOT_DIR={{EXPORT_ROOT_DIR}}
TEMPLATES_ROOT_DIR={{TEMPLATES_ROOT_DIR}}
CLIENT_LOGS_DIR={{CLIENT_LOGS_DIR}}
DATABASE_NAME={{DATABASE_NAME}}
ATTACHMENT_MAX_ALLOWED_FILE_SIZE_BYTES={{ATTACHMENT_MAX_ALLOWED_FILE_SIZE_BYTES}}
THREADS_FOR_INDEXING=20
SYNCHRONOUS_CLASSES_FOR_INDEXING=2
PERFORM_INDEXING=TRUE